### ISSUE TITLE
设备那里不准，我的是mac

### ISSUE THREAD

**Issue by coolicer** [mumuy/browser#1]
<img width="1047" alt="wx20170525-131109 2x" src="https://cloud.githubusercontent.com/assets/811078/26436784/ae375144-414b-11e7-8113-cda57c0efd05.png">

**Comment by JellyBool** [comment]
@coolicer 
看一下 https://github.com/mumuy/browser#设备类型 这个。 PC 是指电脑，不是特指 Windows。

**Comment by coolicer** [comment]
@JellyBool 好看，我看漏了旁边还有个
