### ISSUE TITLE
部分浏览器被错误识别为 360 浏览器

### ISSUE THREAD

**Issue by chanjsq** [mumuy/browser#11]
## 被误判的设备

- Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.108 Safari/537.36 2345Explorer/8.8.2.16672
- Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.90 Safari/537.36 2345Explorer/9.1.0.16794
- Mozilla/5.0 (Windows NT 5.1) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.79 Safari/535.11 QIHU THEWORLD
- Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.92 Safari/537.1 LBBROWSER
- Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.84 Safari/537.22 BIDUPlayerBrowser/2.6.2.67 BIDUTN/81031078
- Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.48 Safari/537.36 QQBrowser/7.5.19314.400
- Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 TheWorld 6
- Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 UBrowser/3.1.1644.29 Safari/537.36
- Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 GBrowser/1.2.6.0 Safari/537.17
- Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.11 (KHTML, like Gecko) Chrome/20.0.1132.11 TaoBrowser/3.5 Safari/536.11

**Comment by mumuy** [comment]
你是用真机测试的吗？

**Comment by mumuy** [comment]
目前发现问题的Chrome36内核及以下，会出现误判……
但是LBBROWSER、UBrowser、QQBrowser、2345Explorer应该不包含在里面才对

**Comment by chanjsq** [comment]
我们是跑在一个我们真实项目上，记录下来的用户数据，每天 6 万 PV。不过没有直接用，只用了部分代码：

```js
function getUserAgent() {
  var userAgent = navigator.userAgent;
  if (window.showModalDialog && window.chrome) {
    for (var i = 0; i < navigator.mimeTypes.length; i++) {
        var item = navigator.mimeTypes[i];
        if (item['type'] === 'application/gameplugin') {
            userAgent += ' QIHU 360SE';
            break;
        }
    }
    if (! /360SE/.test(userAgent)) {
        userAgent += ' QIHU 360EE';
    }
  }
  return userAgent;
}
```

然后通过这段代码，直接保存完整 User Agent 到后端数据库。然后发现了上面那些原始 User Agent，也加了 360 UA 的后缀。

**Comment by mumuy** [comment]
那个部分代码可能有点不准，因为里面还有浏览器列表，按优先级匹配，比如同时匹配了chrome和360，判定为360

**Comment by mumuy** [comment]
我的逻辑是判断有没有该浏览器的特征，在靠优先级匹配……如果同时有360和QQ浏览器的特征，但判定UA明显写着QQ浏览器，肯定判定为QQ浏览器啊

**Comment by chanjsq** [comment]
哦哦，这样呀。那我明白了，那再用这样的逻辑验证一下试试。这两天给你结果哈。感谢。
