### ISSUE TITLE
doesnt support nodejs?

### ISSUE THREAD

**Issue by ijandc** [mumuy/browser#12]
Below is your comments on the top of the code
```
/**
 * 浏览器解析，浏览器、Node.js皆可
 * https://github.com/mumuy/browser
 */
```

 I use this script on NodeJs,but `var _window = window||{};` throw error,window is not defined.

**Comment by ijandc** [comment]
```
if(_window.showModalDialog && _window.chrome ){
            var chrome_vision = u.replace(/^.*Chrome\/([\d]+).*$/, '$1');
            if(chrome_vision>36){
                is360 = true;
            }
        }
```



```
 var navigator_top = window.screenTop-window.screenY;
```

these codes cant run on nodejs.

**Comment by ijandc** [comment]
@onlyling six six six
but why are  your codes so same with this author?

**Comment by ijandc** [comment]
@onlyling six six six 
u forked this script
and expand it 2 support node?

**Comment by mumuy** [comment]
应该解决了
