### ISSUE TITLE
兼容模式无法判断360极速浏览器和360安全浏览器

### ISSUE THREAD

**Issue by firKing** [mumuy/browser#17]
在极速模式下，两个浏览器现在是可以区分的，但是在兼容模式下两个浏览器都会被判断成IE，辛苦~

**Comment by zhaosheng808** [comment]
360兼容模式下还是会被识别成ie!...

![image](https://user-images.githubusercontent.com/26834525/50392358-c430f400-0788-11e9-9a8a-80c6072e3cc0.png)

**Comment by mumuy** [comment]
模式切换本身就是模拟，不做这方面处理
