### ISSUE TITLE
最新版的Opera被识别为Baidu

### ISSUE THREAD

**Issue by skyorbit0** [mumuy/browser#18]
`Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 OPR/56.0.3051.43 (Edition Baidu)`

Opera的UA里出现了Baidu导致被识别为Baidu，把js里hash对象中`Opera`放到`Baidu`后面应该就能解决了。

**Comment by mumuy** [comment]
谢谢～已修改
