### ISSUE TITLE
IE相容模式下的真實版本 True Version of IE in CompatibilityMode 

### ISSUE THREAD

**Issue by shyangs** [mumuy/browser#20]
https://github.com/Gavin-Paolucci-Kleinow/ie-truth

Gavin-Paolucci-Kleinow 的 ie-truth 能判斷出IE相容模式下的真實版本, 能把這個抄過來嗎.

當然目前的 ActingVersion 還是要保留的.

**Comment by mumuy** [comment]
本身是模拟，不做这方面处理
