### ISSUE TITLE
android端无法区分360浏览器和Chrome浏览器

### ISSUE THREAD

**Issue by 2173432565** [mumuy/browser#21]
android端360浏览器和360极速浏览器都会识别为Chrome浏览器，还有华为自带的浏览器会识别为safari浏览器

**Comment by mumuy** [comment]
脚本功能本身不做华为的识别

**Comment by 2173432565** [comment]
android端360浏览器和360极速浏览器都会识别为Chrome浏览器，请问这个有办法解决吗？

**Comment by mumuy** [comment]
有UA头吗？

**Comment by 2173432565** [comment]
不知道为什么，图片上传不了：
Mozilla/5.0 (Linux; Android 8.0.0; MHA-AL00 Build/HUAWEIMHA-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.97 Mobile Safari/537.36

**Comment by 2173432565** [comment]
这是360极速浏览器，页面显示的ua头

**Comment by 2173432565** [comment]
![360](https://user-images.githubusercontent.com/42538201/53537223-3389e200-3b44-11e9-8c84-8d1a142fb737.jpg)
Android版 360极速浏览器

**Comment by mumuy** [comment]
暂时没有办法，没有特征值

**Comment by 2173432565** [comment]
嗯，我也是网上找了好久，没有找到可行的方法，网上好多以前的方法都已经失效了，360清除了浏览器UA里面所有360的痕迹

**Comment by mumuy** [comment]
360 PC版本可以识别的，就是移动版本识别不了

**Comment by 2173432565** [comment]
是的，我试过pc版的是没问题的。
关于原始问题的第二个问题，虽然没办法判断华为自带浏览器，但是建议，如果包含android 或 Chrome 就排除掉safari浏览器，希望这个越做越好
