### ISSUE TITLE
还有个问题，2345浏览器电脑端打开会有 saveData  undefined的报错

### ISSUE THREAD

**Issue by onlyscv** [mumuy/browser#27]
2345浏览器电脑端打开会有 saveData  undefined的报错，页面也无法显示。
你的在线测试的那个也是无法显示。

![QQ截图20190710181452](https://user-images.githubusercontent.com/33649764/60961431-b6b31400-a33e-11e9-8324-3a5501ce8d2e.jpg)

**Comment by onlyscv** [comment]
不知道其他浏览器是不是还有类似的报错，没有再做具体的测试。

**Comment by mumuy** [comment]
修复了，谢谢
