### ISSUE TITLE
使用手机百度浏览器无法获取信息

### ISSUE THREAD

**Issue by Moodyqiqi** [mumuy/browser#28]
使用手机百度浏览器无法获取信息，
使用window.navigator.userAgent输出信息如下：
Mozilla/5.0 (Linux; Android 8.0.0; EDI-AL10 Build/HUAWEIEDISON-AL10; wv) AppleWebKit/537.36 
(KHTML, like Gecko) Version/4.0 Chrome/63.0.3239.83 Mobile Safari/537.36 T7/11.11 baiduboxapp/11.11.0.12 (Baidu; P1 8.0.0)

**Comment by mumuy** [comment]
谢谢，已修复
