### ISSUE TITLE
win10 浏览器打开, 识别为 win7 系统

### ISSUE THREAD

**Issue by FollowTheTrend** [mumuy/browser#29]
win10 浏览器打开, 识别为 win7 系统

**Comment by FollowTheTrend** [comment]
使用的最新版微信, 识别的 user-agent 为
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36 QBCore/3.53.1159.400 QQBrowser/9.0.2524.400 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 MicroMessenger/6.5.2.501 NetType/WIFI WindowsWechat

**Comment by mumuy** [comment]
谢谢，已修复
