### ISSUE TITLE
将基于Chromium的edge浏览器识别为chrome浏览器了？

### ISSUE THREAD

**Issue by luojinghui** [mumuy/browser#31]
Chromium的edge浏览器马上发布，在edge dev版本测试，识别为chrome浏览器了。

useragent：
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3952.0 Safari/537.36 Edg/80.0.320.4"

**Comment by mumuy** [comment]
谢谢反馈，已添加匹配

**Comment by luojinghui** [comment]
thanks
