### ISSUE TITLE
readme中typo

### ISSUE THREAD

**Issue by TheCGDF** [mumuy/browser#34]
```
DingTakl - 钉钉手机客户端
```
应该为DingTalk
以及，是否可以考虑支持检测欧朋浏览器（北界无限（北京）软件有限公司）？

**Comment by mumuy** [comment]
欧朋浏览器不就是Opera吗？

**Comment by TheCGDF** [comment]
> 欧朋浏览器不就是Opera吗？

不，欧朋现在是北界无限搞的，这两个浏览器有些不同，举个例子，欧朋屏蔽了996.icu的访问，而Opera没有
参见：https://github.com/996browser/996.BROWSER

**Comment by mumuy** [comment]
不做了，就认Opera

**Comment by TheCGDF** [comment]
遗憾。
