### ISSUE TITLE
360极速浏览器识别失败

### ISSUE THREAD

**Issue by xiekun1992** [mumuy/browser#36]
![60477287a134c89c16a9645bc628dabc](https://user-images.githubusercontent.com/10451769/72312135-0c87c080-36c2-11ea-8ece-2fa266efa25e.png)

**Comment by mumuy** [comment]
![无标题](https://user-images.githubusercontent.com/7868746/78805296-d3769800-79f3-11ea-9472-07b3b6433161.png)
我这边显示没问题，不知道怎么回事了，没法复现
