### ISSUE TITLE
使用Vivaldi打开，为什么显示当前浏览器是Chrome

### ISSUE THREAD

**Issue by iFCoder** [mumuy/browser#37]
还有其他办法判断是Vivaldi浏览器吗？

**Comment by TheCGDF** [comment]
https://vivaldi.com/blog/user-agent-changes/
vivaldi为了避免被“负优化”，user agent已经全部模仿chrome了

**Comment by chygfm** [comment]
Vivaldi 识别不出来 为 chrome

**Comment by wnose** [comment]
Vivalid或者Brave可以使用navigator.userAgentData.brands[2]来进行判断

**Comment by mumuy** [comment]
已添加识别特征
