### ISSUE TITLE
Mobile of Huawei

### ISSUE THREAD

**Issue by simo-an** [mumuy/browser#38]
The ways to judge if it's Huawei browser is
```
'Huawei': u.indexOf('HuaweiBrowser') > -1||u.indexOf('HUAWEI') > -1
```

But i found that other browsers installed on huawei also contain `HUAWEIIJKM`.

Huawei's default browser's kernal is X5(QQBrowser), so i think regarding it as QQBrowser may be more reasonable.

**Comment by mumuy** [comment]
most browser is bese on Chromium, but I can't regarding it as Chromium

**Comment by VYuLinLin** [comment]
楼上的意思应该是这种判断`u.indexOf('HuaweiBrowser') > -1||u.indexOf('HUAWEI') > -1`不能正确判断是否是华为浏览器。
因为华为手机上安装的其他浏览器，userAgent也包含HUSWEI这个字段，比如我的华为手机，自带的浏览器和安装的UC浏览器，判断都不正确
