### ISSUE TITLE
希望可以发到npm并增加TS支持

### ISSUE THREAD

**Issue by bowencool** [mumuy/browser#46]

**Comment by onlyling** [comment]
有时间用 TypeScript 写一下，前段时间尝试重新写，[onlyling-browser](https://github.com/onlyling/browser)

后来发现一个功能相似的库[ua-parser-js](https://github.com/faisalman/ua-parser-js) -、-

**Comment by bowencool** [comment]
> 有时间用 TypeScript 写一下，前段时间尝试重新写，[onlyling-browser](https://github.com/onlyling/browser)
> 
> 后来发现一个功能相似的库[ua-parser-js](https://github.com/faisalman/ua-parser-js) -、-

ua-parser-js我也试过，准确度（国内）不如百度的那个ua-device，可惜不维护了。我现在就是用ua-device，不停地添加修正代码。

**Comment by tonytony2020** [comment]
> 有时间用 TypeScript 写一下，前段时间尝试重新写，[onlyling-browser](https://github.com/onlyling/browser)
> 
> 后来发现一个功能相似的库[ua-parser-js](https://github.com/faisalman/ua-parser-js) -、-

+1

作者留个二维码，如果你们实现了。我想打赏

**Comment by onlyling** [comment]
> > 有时间用 TypeScript 写一下，前段时间尝试重新写，[onlyling-browser](https://github.com/onlyling/browser)
> > 后来发现一个功能相似的库[ua-parser-js](https://github.com/faisalman/ua-parser-js) -、-
> 
> +1
> 
> 作者留个二维码，如果你们实现了。我想打赏

很早就写了一个版本。

今天更新了一下，可以参考 [onlyling / browser](https://github.com/onlyling/browser)，最新的查看 mumuy 分支。

目前结合 [ua-parser-js / test](https://github.com/faisalman/ua-parser-js/tree/master/test) 里面的测试数据，还有比较多的场景不通过。

**Comment by yangtianxia** [comment]
typescript 重写的一个库 [ua-browser](https://github.com/yangtianxia/ua-browser)

**Comment by mumuy** [comment]
已增加npm包
https://www.npmjs.com/package/browser-tool

**Comment by shushenghong** [comment]
typescript里咋引入？

**Comment by mumuy** [comment]
> typescript里咋引入？

直接引入啊，不是超集吗
