### ISSUE TITLE
360 极速浏览器 Mac 版 12.2 无法正确检测

### ISSUE THREAD

**Issue by netgc** [mumuy/browser#47]
您好，详细信息如下：

浏览器下载地址：
https://down.360safe.com/cse/360Browser_for_mac_12.2.1636.0.dmg
系统版本：macOS Big Sur 11.1

检测结果：
Mozilla/5.0 (Macintosh; Intel Mac OS X -1_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

浏览器	版本	内核	操作系统	设备	语言
Chrome	78.0.3904.108	Blink	Mac OS Mozilla/5.0 (Macintosh; Intel Mac OS X -1.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36	PC	zh_CN
项目地址 Useragent分析 返回首页

<img width="915" alt="360" src="https://user-images.githubusercontent.com/41975268/107464746-e28e1f80-6b9b-11eb-97d1-01b8b7629b27.png">

IP 138 UserAgent分析和查询
服务端获取的UserAgent：
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_16_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
客户端获取的UserAgent：
Mozilla/5.0 (Macintosh; Intel Mac OS X -1_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
浏览器信息：
名称	版本号	渲染引擎	操作系统

Chrome	78.0.3904.108	WebKit 537.36	Mac OS undefined

<img width="895" alt="3602" src="https://user-images.githubusercontent.com/41975268/107464782-f0dc3b80-6b9b-11eb-9db7-49871e131411.png">

**Comment by fz6m** [comment]
```js
var is360 = function () {
  var u = 'undefined'
  try {
    return (
      (typeof chrome != u &&
        typeof chrome.webstorePrivate != u &&
        typeof chrome.webstorePrivate.beginInstallWithManifest3 != u) ||
      ~navigator.userAgent.toLowerCase().indexOf('360ee')
    )
  } catch (e) {}
  return 0
}
```

可使用此代码判断 360 浏览器。

**Comment by mumuy** [comment]
已添加对 360浏览器Mac版判断的支持
