### ISSUE TITLE
liebao 猎豹识别不出来？

### ISSUE THREAD

**Issue by chygfm** [mumuy/browser#48]
liebao 猎豹识别不出来
device: "PC"
language: "zh_CN"
engine: "Blink"
browser: "Chrome"
os: "Windows"
osVersion: "7"
version: "79.0.3945.79"

还是显示chrome.

**Comment by Async-Lee** [comment]
110行代码修改如下可识别猎豹浏览器：
var is360 = false;
        ### if(_window.chrome){
            var chrome_version = u.replace(/^.*Chrome\/([\d]+).*$/, '$1');
            var isLiebao = false;
            for (var key in _window.chrome) {
                if(key.indexOf('Liebao')>-1) {
                    isLiebao = true;
                }
            }
            if(isLiebao){
                match['Liebao'] = true;
            }else if(_window.chrome.adblock2345||_window.chrome.common2345){
                match['2345Explorer'] = true;
            }else if(_mime("type", "application/360softmgrplugin")||_mime("type", "application/mozilla-npqihooquicklogin")){
                is360 = true;
            }else if(chrome_version>36&&_window.showModalDialog){
                is360 = true;
            }else if(chrome_version>45){
                is360 = _mime("type", "application/vnd.chromium.remoting-viewer");
                if(!is360&&chrome_version>=69){
                    is360 = _mime("type", "application/hwepass2001.installepass2001")||_mime("type", "application/asx");
                }
            }
        }

**Comment by chygfm** [comment]
var chrome_version =u.replace(/^.*Chrome\/([\d]+).*$/, '$1');

**Comment by chygfm** [comment]
var chrome_version =u.replace(/^.*Chrome\/([\d]+).*$/, '$1');

应该是原始的，这句代码？
