### ISSUE TITLE
Firefox for Mac 版本判断错误

### ISSUE THREAD

**Issue by vndroid** [mumuy/browser#58]
火狐浏览器正式版会被判断为 Firefox Nightly 

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0`

并且系统版本也判断错误 `Mac OS 10`

**Comment by mumuy** [comment]
未找到合适的判断方式，内部判断方法只对Mozilla官网有效，已取消Firefox Nightly判断
