### ISSUE TITLE
nodejs直接报错

### ISSUE THREAD

**Issue by yzytmac** [mumuy/browser#62]
require('./Browser')引入js，直接报错
ReferenceError: navigator is not defined
错误地方是if(navigator.userAgentData)这里，不是很熟悉nodejs，也不知道如何排查，还望楼主能解答一下，不胜感激

**Comment by onlyling** [comment]
https://github.com/mumuy/browser/blob/master/Browser.js#L32
这里开始的 `navigator` 变量应该替换为 `_navigator `

**Comment by mumuy** [comment]
@onlyling 谢谢指出，加新功能忘记了特殊判断
