### ISSUE TITLE
国产浏览器 兼容内核访问失败

### ISSUE THREAD

**Issue by JoyNop** [mumuy/browser#63]
![WX20221111-093300@2x](https://user-images.githubusercontent.com/25074750/201243058-1cabb85f-d671-4fdd-b38f-5588e9ccc27b.png)

**Comment by JoyNop** [comment]
edge ie模式似乎也无法使用了

**Comment by mumuy** [comment]
已修复，居然是兼容模式不支持箭头函数的写法。。。
