### ISSUE TITLE
此处代码少了个逗号，导致代码执行报错。

### ISSUE THREAD

**Issue by caiweiming** [mumuy/browser#68]
https://github.com/mumuy/browser/blob/778f850cc0efe860ff75c5a4662f2b04090ce6da/browser.js#L445

**Comment by caiweiming** [comment]
448行也少了一个逗号

**Comment by mumuy** [comment]
哈哈，我太粗心了……一直懒得加单元测试，看来需要加了

**Comment by mumuy** [comment]
谢谢啦

**Comment by caiweiming** [comment]
哈哈，跟我一样，我也是好懒，从来没加测试单元。不过因为你的项目是可以直接用jsdelivr引进来用，加上你没创建tag或者版本号，所以只能直接用master版本，这就导致如果你的代码一旦有问题，别人引用你的项目也可能有问题，哈哈。
建议你可以适当的给项目发布版本号或者加个tag，这样就算你的master分支有问题，之前因为的也不会有太大问题。当然，像你说的，加个单元测试也是可以。
感谢你的项目，给我带来了便利。

**Comment by mumuy** [comment]
不瞒你说，我才知道tag是这么用的……我之间一直以为只是打给标记，不知道可以按这个标记jsdelivr引用

**Comment by mumuy** [comment]
涨知识了

**Comment by caiweiming** [comment]
嗯嗯，确定当前版本的代码没问题，就可以给项目发布一个版本号，方便需要引用的人，可以随意选择不同的代码版本。
