### ISSUE TITLE
双核浏览器有bug - For some of the dual kernel browser, there are bugs

### ISSUE THREAD

**Issue by crlang** [mumuy/browser#7]
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; InfoPath.3; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; SE 2.X MetaSr 1.0; rv:11.0) like Gecko

例如上方这个是搜狗的兼容模式，IE 11 兼容模式，但返回的是搜狗。其实返回的是最后一个 rv:11.0
For example, this is the Sogou compatibility mode, IE 11 compatible mode, but the return is Sogou. In fact, the return is the last rv: 11.0

**Comment by mumuy** [comment]
目的就是为了识别什么浏览器啊，不是为了解析UA，当然能返回搜狗是第一选择
