### ISSUE TITLE
移动端谷歌浏览器检测操作系统不对

### ISSUE THREAD

**Issue by 1979044994** [mumuy/browser#70]
同一个设备使用五个不同浏览器，谷歌检测的系统版本和其它浏览器检测的不同，版本查阅不对。pc对windos11检测为win10

**Comment by mumuy** [comment]
没看明白，移动端谷歌浏览器检测windows11？

**Comment by 1979044994** [comment]
> 不是，是同一个移动端的设备使用不同的浏览器去检测，但是检测出来的结果是不一样的。pc端使用检测win11 的设备检测的结果告诉我是win10

**Comment by mumuy** [comment]
windows的浏览器判断条件变成异步的了，你可以使用browser.getInfo().then(function(data){   });获取相关信息
