### ISSUE TITLE
Mac上的360极速浏览器被识别为Safari

### ISSUE THREAD

**Issue by Ustinians** [mumuy/browser#73]
您好，当我在进行浏览器设备的检测的时候，360极速浏览器检测结果为Safari

Navigator.userAgent内容如下：
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15

<img width="976" alt="image" src="https://github.com/mumuy/browser/assets/85676101/93a11dc1-60b9-49ca-929f-cdb968e22aba">

**Comment by charle00001** [comment]
居然有人在Mac上用360？？？这种稀缺生物2023年见的不多了

**Comment by Ustinians** [comment]
公司的需求没办法😢

**Comment by vndroid** [comment]
这个问题是因为 360 本身伪装为 Safari 的 UA 信息，除非有什么私有 APi 能针对性判断 360，否则无解。

**Comment by mumuy** [comment]
> 这个问题是因为 360 本身伪装为 Safari 的 UA 信息，除非有什么私有 APi 能针对性判断 360，否则无解。

已添加对 Mac版360浏览器的判断
