### ISSUE TITLE
win10 360安全浏览器检测失效，识别为chrome浏览器

### ISSUE THREAD

**Issue by WvvvWv** [mumuy/browser#81]
![Clip_2024-04-12_13-45-39](https://github.com/mumuy/browser/assets/40822202/7b224fd2-9e4f-4530-ac68-ee7fe7750f96)

**Comment by mumuy** [comment]
能在控制台打印下“window.navigator.plugins”这个变量的详情吗？我的系统和浏览器版本和你的一模一样，没出现这个问题

**Comment by WvvvWv** [comment]
> 能在控制台打印下“window.navigator.plugins”这个变量的详情吗？我的系统和浏览器版本和你的一模一样，没出现这个问题

抱歉忘记关闭issus了，我那天重启了一下360再进去检测就显示正常了，抱歉。
