### ISSUE TITLE
IE 11 判断成了 Sogouspider

### ISSUE THREAD

**Issue by yf339339** [mumuy/browser#83]
IE 11 判断成了 Sogouspider
![image](https://github.com/mumuy/browser/assets/28554074/768d88ba-cc02-4ebb-ba7f-853259215fed)
![image](https://github.com/mumuy/browser/assets/28554074/07aea7aa-c2e7-4210-babb-b921b55bec48)

**Comment by mumuy** [comment]
谢谢反馈，搬代码的时候复制错了，已修复
