### ISSUE TITLE
chrome-extension://invalid

### ISSUE THREAD

**Issue by QiaoXiaofeng** [mumuy/browser#87]
browser-tool v1.2.8
GET chrome-extension://invalid/ net::ERR_FAILED

**Comment by mumuy** [comment]
那个是为了测试是否是Vivaldi浏览器发的请求，网络错误说明不是这个浏览器呀，没问题的

**Comment by Qiulin-Git** [comment]
> 那个是为了测试是否是Vivaldi浏览器发的请求，网络错误说明不是这个浏览器呀，没问题的

我觉得如果出现这个错误是正常的，那应该用 try{ } catch (err){	console.log(err); }  去处理，不能在浏览器里看到报错才对

**Comment by mumuy** [comment]
> > 那个是为了测试是否是Vivaldi浏览器发的请求，网络错误说明不是这个浏览器呀，没问题的
> 
> 我觉得如果出现这个错误是正常的，那应该用 try{ } catch (err){ console.log(err); } 去处理，不能在浏览器里看到报错才对

试了下，还真不行，try catch屏蔽不了

**Comment by yangyl568** [comment]
请问为什么要默认开启这个检测？

**Comment by mumuy** [comment]
> 请问为什么要默认开启这个检测？

检测360浏览器的一种方法呀

**Comment by yangyl568** [comment]
<img width="841" alt="image" src="https://github.com/user-attachments/assets/9f71f03a-7223-40af-93e8-def0746db909">
我是谷歌浏览器，然后也有这个提示。怎么可以关掉？

**Comment by mumuy** [comment]
> <img alt="image" width="841" src="https://private-user-images.githubusercontent.com/19680934/369291276-9f71f03a-7223-40af-93e8-def0746db909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MTcyNDUsIm5iZiI6MTcyNjgxNjk0NSwicGF0aCI6Ii8xOTY4MDkzNC8zNjkyOTEyNzYtOWY3MWYwM2EtNzIyMy00MGFmLTkzZTgtZGVmMDc0NmRiOTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA3MjIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzMGZjYjVkYTQ2Mzg4NjQyN2ZlZmJlYjJmZDMwYjk2MmYyYjlkZTdkNjlhYzUyOTMyMjU2MmIzZGE4ZThkMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VUkcnvsUo8H8DqynxDjIHU-4VurN02hoNgLcRDlO23E"> 我是谷歌浏览器，然后也有这个提示。怎么可以关掉？

这是正常逻辑呀！在没有测试之前，哪里知道是谷歌还是360浏览器呢？因为360浏览器用的UA就是chrome的UA，无法单纯从UA分析出来
