### ISSUE TITLE
mac下的QQ浏览器会被识别为QQ且无浏览器版本信息

### ISSUE THREAD

**Issue by Dorisfhy** [mumuy/browser#88]
navigator.userAgent信息如下：'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 QQBrowser/5.0.6.205'

JSON.stringify(navigator.userAgentData)信息如下：
'{"brands":[{"brand":"(Not(A:Brand","version":"8"},{"brand":"Chromium","version":"98"}],"mobile":false}'

-------------关于QQ浏览器-----------------------------------
QQ浏览器  版本 5.0.6.205（正式版本） (arm64)
内核 Chromium 98.0.4758.102

**Comment by mumuy** [comment]
你用的是旧版吧？这个问题再之前修复过
https://github.com/mumuy/browser/commit/ed5f599cf4d11f87a6ae618285dad910d7fb5541
