### ISSUE TITLE
信息识别不准？

### ISSUE THREAD

**Issue by yangyl568** [mumuy/browser#89]
我的浏览器信息：
<img width="375" alt="image" src="https://github.com/user-attachments/assets/b437baa5-d976-439f-b529-72b6485764ae">
<img width="185" alt="image" src="https://github.com/user-attachments/assets/4b051e15-0052-48c4-bac3-14c01746871b">

这个是检测出来的信息：
<img width="955" alt="image" src="https://github.com/user-attachments/assets/930b6e49-a6c9-4093-a045-a9325715f8f2">

版本和操作系统、系统平台都不准确？

**Comment by mumuy** [comment]
根据UA判断，不准的是你的系统呀
