### ISSUE TITLE
GET chrome-extension://invalid/ net::ERR_FAILED？

### ISSUE THREAD

**Issue by cccEric** [mumuy/browser#94]
<img width="1699" alt="image" src="https://github.com/user-attachments/assets/ae169442-300d-413c-b135-39e195f43cc5">
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/ba425421-baa3-4086-8483-45171d91bd3e">

**Comment by mumuy** [comment]
This is a way to test your browser
