### ISSUE TITLE
npmjs中的最新版是1.3.1，没有getFingerprint()函数。但https://passer-by.com/browser/中使用的是1.3.2

### ISSUE THREAD

**Issue by valuetodays** [mumuy/browser#97]
## 背景

访问`https://github.com/mumuy/browser/`，里面有安装方式`npm install browser-tool`，但安装的版本是1.3.1，去[npmjs](https://www.npmjs.com/package/browser-tool)看了一下，最新版是`1.3.1`。而[【项目主页】](https://passer-by.com/browser/)中使用的是`1.3.2`。

## 问题

1.3.1版本中没有getFingerprint()

## 结论

希望能发布最新版到npmjs中。

**Comment by mumuy** [comment]
有时候想着稳定点再更新，后来就忘了……已更新啦~
